person:
  name: Leo_Liu
  age: 18
server:
  port: 8081
# datasource
spring:
  datasource:
    url: jdbc:mysql://8.134.201.230:3306/reservationsys?characterEncoding=UTF-8
    username: ReservationSys
    password: ydyd3154
    driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis
mybatis:
#  config-location:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper的映射文件路径
  type-aliases-package: com.dragon.springbootmybatis.entity.SeminarBooking # 用以起别名

